Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\randa\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\randa\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\randa\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\randa\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\randa\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\randa\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pd.set_option('precision', 8)

pd.DataFrame({
    'Numerical': [F(x), F(x, 1), F(x,2), F(x, -1)],
    'Analytic': [f(x), d1(x), d2(x), np.exp(1)-1]},
    index = ['Function', 'First Derivative', 'Second Derivative', 'Definite Integral']
)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mOptionError[0m                               Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_24744\2142931887.py[0m in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[1;33m [0mpd[0m[1;33m.[0m[0mset_option[0m[1;33m([0m[1;34m'precision'[0m[1;33m,[0m [1;36m8[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m pd.DataFrame({
[0;32m      4[0m     [1;34m'Numerical'[0m[1;33m:[0m [1;33m[[0m[0mF[0m[1;33m([0m[0mx[0m[1;33m)[0m[1;33m,[0m [0mF[0m[1;33m([0m[0mx[0m[1;33m,[0m [1;36m1[0m[1;33m)[0m[1;33m,[0m [0mF[0m[1;33m([0m[0mx[0m[1;33m,[0m[1;36m2[0m[1;33m)[0m[1;33m,[0m [0mF[0m[1;33m([0m[0mx[0m[1;33m,[0m [1;33m-[0m[1;36m1[0m[1;33m)[0m[1;33m][0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m     'Analytic': [f(x), d1(x), d2(x), np.exp(1)-1]},

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\pandas\_config\config.py[0m in [0;36m__call__[1;34m(self, *args, **kwds)[0m
[0;32m    254[0m [1;33m[0m[0m
[0;32m    255[0m     [1;32mdef[0m [0m__call__[0m[1;33m([0m[0mself[0m[1;33m,[0m [1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 256[1;33m         [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m__func__[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    257[0m [1;33m[0m[0m
[0;32m    258[0m     [1;33m@[0m[0mproperty[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\pandas\_config\config.py[0m in [0;36m_set_option[1;34m(*args, **kwargs)[0m
[0;32m    147[0m [1;33m[0m[0m
[0;32m    148[0m     [1;32mfor[0m [0mk[0m[1;33m,[0m [0mv[0m [1;32min[0m [0mzip[0m[1;33m([0m[0margs[0m[1;33m[[0m[1;33m:[0m[1;33m:[0m[1;36m2[0m[1;33m][0m[1;33m,[0m [0margs[0m[1;33m[[0m[1;36m1[0m[1;33m:[0m[1;33m:[0m[1;36m2[0m[1;33m][0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 149[1;33m         [0mkey[0m [1;33m=[0m [0m_get_single_key[0m[1;33m([0m[0mk[0m[1;33m,[0m [0msilent[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    150[0m [1;33m[0m[0m
[0;32m    151[0m         [0mo[0m [1;33m=[0m [0m_get_registered_option[0m[1;33m([0m[0mkey[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\pandas\_config\config.py[0m in [0;36m_get_single_key[1;34m(pat, silent)[0m
[0;32m    114[0m         [1;32mraise[0m [0mOptionError[0m[1;33m([0m[1;34mf"No such keys(s): {repr(pat)}"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    115[0m     [1;32mif[0m [0mlen[0m[1;33m([0m[0mkeys[0m[1;33m)[0m [1;33m>[0m [1;36m1[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 116[1;33m         [1;32mraise[0m [0mOptionError[0m[1;33m([0m[1;34m"Pattern matched multiple keys"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    117[0m     [0mkey[0m [1;33m=[0m [0mkeys[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m    118[0m [1;33m[0m[0m

[1;31mOptionError[0m: 'Pattern matched multiple keys'
OptionError: 'Pattern matched multiple keys'

